title: "Lyric Bowditch | Independent Podcast Producer and Editor"
logo: /assets/HEADSHOT 2.jpg
description: "Lyric Bowditch is a Brooklyn-based podcast producer and editor."
url: "https://www.lyricbowditch.com"
theme: jekyll-theme-minimal
